### ISSUE TITLE
Suivi des coûts

### ISSUE THREAD

**Issue by webjib** [bokub/ha-linky#2]
Tout d'abord, bravo pour cette extension qui marche parfaitement bien !

Dans le paramètre du tableau de bord Energie, quand on choisit la source de données Linky, on ne peut pas choisir de suivre les coûts, notamment en indiquant un coût statique. Tu crois que c'est facile à ajouter de ton coté ?

<img width="401" alt="Capture d'écran 2023-09-04 à 18 28 55" src="https://github.com/bokub/ha-linky/assets/33569886/534612ba-7b7d-46a7-9101-f9f9df576c56">

**Comment by bokub** [comment]
Effectivement, mais c’est une limitation de **Home Assistant**, qui interdit de paramétrer un prix sur des statistiques « externes » (c’est à dire non créées par un `sensor`).

J’ai essayé de trouver plus d’informations et / ou des moyens de contourner cette limitation mais c’est assez difficile de trouver de la documentation. J'ai également demandé des infos [ici](https://github.com/home-assistant/frontend/issues/17807), puis [ici](https://github.com/home-assistant/frontend/pull/15205#discussion_r1314283542) puis [ici](https://community.home-assistant.io/t/import-old-energy-readings-for-use-in-energy-dashboard/341406/72), mais sans succès pour l'instant.

Je l'aisse l'issue ouverte tant que ce problème n'est pas résolu

**Comment by webjib** [comment]
Merci pour ta réactivité !

**Comment by webjib** [comment]
Pour moi ton astuce ne fonctionne pas.
 
 @bokub : penses tu qu’il serait envisageable d’exposer les données comme un sensor à place (ou en plus). Car actuellement les données ne sont exploitables que dans le tableau de bord Énergie, et ça pourrait résoudre ce problème de suivi des coûts.

**Comment by bokub** [comment]
Oui effectivement, il serait possible de sauvegarder le coût de chaque journée ou demi-heure dans une entité à part, mais je me demande comment faire pour que ce soit configurable facilement par tous les utilisateurs sachant qu'il faut gérer:
- Les tarifs base (facile)
- Les HP / HC sachant que les plages horaires dépendent de chaque contrat
- Les tarifs tempo (compliqué, car le tarif serait stocké par une entité gérée par l'utilisateur)

J'ai réfléchi à un système de template à fournir à l'addon et qui calculerait le prix pour une plage horaire donnée. ça pourrait marcher pour tout le monde mais j'ai peur que ce soit une usine à gaz et j'ai pas eu le temps de creuser plus. L'autre solution serait de ne pas gérer les tempo, mais c'est pareil je n'ai pas trouvé de format de config qui soit élégant. Je suis preneur d'idées / suggestions si vous en avez

**Comment by SIM0N-F** [comment]
Bonjour @bokub, coté MyEnedis ils fournissent un panel de conf qui prend en compte ses paramètres:
![image](https://github.com/bokub/ha-linky/assets/25002902/a8a93ff4-2433-417a-85db-9d8f3a796deb)

Le paramétrage des plages horaires HC n'est pas des plus sympa en terme d'UX mais ça reste facilement accessible je trouve.

**Comment by Smokwithme** [comment]
Bonjour, 
Avez vous trouvé une solution pour fixer un prix au moins pour l'abonnement de base. J'ai tenté de créer un capteur avec la valeur en state mais même si je peux ajouter l'entité dans le paramètre de cout, le calcul ne se fait pas.
Merci d'avance

**Comment by Jacquiers687** [comment]
Bonjour
oui j'ai compris comment cela fonctionnait hier.
SI on récupere les données du linky via une intégration, ca ne fonctionnera jamais.
Moi j'ai refait des sensor, de type energy, que je met à jour toutes les 30 min.
A coté de celà j'ai fait un template pour le prix, et quand je les integre tous les deux dans HA, et ca fonctionne !
```
template:
  - sensor: 
      - name: "Prix du Kwh en euros"
        state_class: 'measurement'
        unit_of_measurement: "EUR/kWh"
        unique_id: 'prix_kwh_bleu'
        icon: mdi:currency-eur 
        state: "{% if ( ((now().strftime('%H:%M') >= '01:30') and (now().strftime('%H:%M') < '07:30'))or((now().strftime('%H:%M') >= '12:30') and (now().strftime('%H:%M') < '14:30')) ) -%} {{states.input_number.prix_heure_creuse_kwh.state | float(default=0)}} {%- else -%} {{states.input_number.prix_heure_pleine_kwh.state | float(default=0)}} {%- endif %} "     

```
