### ISSUE TITLE
Consommation par tranches TEMPO

### ISSUE THREAD

**Issue by SeeeeebDe** [bokub/ha-linky#47]
Bonjour,

Merci pour cette application simple et efficace !

J'ai une requête de fonctionnalité : 
intégrer la gestion de l'option TEMPO en post-traitant les données Enedis pour alimenter des sous compteurs bleu HP/HC, rouge HP/HC et blanc HP/HC.

En effet, je n'ai pas trouvé de moyen de le faire. Les seules possibilités que j'ai trouvées sont des intégrations qui nécessitent de capter la consommation en direct (pinces, ou dongle sur le Linky) et qui jouent ensuite avec des bascules vers chaque sous compteur.

Serait-ce faisable ? Si pas possible de l'intégrer, voyez-vous une alternative toujours en utilisant la remontée d'info que fait HA-Linky ?

**Comment by Mavyre** [comment]
Moi j'ai trouvé une alternative... En quelques sortes. J'ai créé trois fichiers `options.json` qui contiennent des tableaux `costs` différents, par exemple pour le jour bleu : 
```
{
  "meters": [
    {
      "prm": "xxxx",
      "token": "xxxx",
      "name": "Linky consumption",
      "action": "sync",
      "production": false
    }
  ],
  "costs": [
    {
      "price": 0.1296,
      "before": "06:00"
    },
    {
      "price": 0.1609,
      "after": "06:00",
      "before": "22:00"
    },
    {
      "price": 0.1296,
      "after": "22:00"
    }
  ]
}
```
J'ai créé trois shell_commands pour mettre le bon `options.json` : 
```
shell_command:
  ha_linky_config_blue: cp /mnt/ha-addons/linky/template/options_blue.json /mnt/ha-addons/linky/options.json
  ha_linky_config_white: cp /mnt/ha-addons/linky/template/options_white.json /mnt/ha-addons/linky/options.json
  ha_linky_config_red: cp /mnt/ha-addons/linky/template/options_red.json /mnt/ha-addons/linky/options.json
```
J'ai ensuite installé depuis HACS le plugin "RTE Tempo" (https://github.com/hekmon/rtetempo). Puis, pour rester dans HA sans aucune autre dépendance, j'ai créé trois automations (une pour chaque jour), qui ressemble à ça : 
<img width="1172" alt="image" src="https://github.com/user-attachments/assets/d6ca23d8-9862-49b5-b1f1-2a3ab49cd4bb">

En écrivant ça, je me suis rendu compte de deux choses sur cette méthode : 
1. On peut optimiser ça en utilisant une commande de type `sed` plutôt que d'utiliser des templates
2. La tranche de 0h-6h n'est pas bonne puisqu'elle est censé utiliser la couleur du jour d'avant. Il faudrait utiliser le calendar de RTE Tempo pour aller chercher l'historique
