### ISSUE TITLE
Bug: problème à l'import au premier démarrage

### ISSUE THREAD

**Issue by sambonbonne** [bokub/ha-linky#51]
Bonjour,

Je ne sais pas si mon ticket sera accepté puisque j'installe l'addon de manière conteneurisées (je construis l'image `standalone.Dockerfile` et je l'utilise sur Kubernetes sur une carte en ARM64) mais sait-on jamais.

J'ai les logs suivants :
```log
HA Linky is starting
Connection with Home Assistant established
PRM [REDACTED] found in configuration for consumption
[04/07 12:14] New PRM detected, historical consumption data import is starting
Cannot find folder /addon_configs/cf6b56a3_linky
TypeError: Cannot read properties of undefined (reading 'length')
```

Du coup, le process plante et Kubernetes le redémarre (rien d'inquiétant si ce n'est que ça le redémarre inutilement en boucle puisque l'erreur persiste).

Est-ce que ça peut être dû à une mauvaise configuration ?

À savoir que j'ai bien setup `WS_URL` et `SUPERVISOR_TOKEN`, le pont entre HA et HA-Linky semble OK.

Voici mon fichiers `/data/options.json` : 

```json
{
  "meters": [
    {
      "prm": "[REDACTED]",
      "token": "[REDACTED]",
      "name": "Linky maison",
      "action": "sync",
      "production": false
    }
  ]
}
```

Pour information, j'ai tenté de renouveler le token Conso API, ça n'a rien changé. Idem pour le token de superviseur, sans succès.

Merci d'avance pour tout aide supplémentaire, je serais ravi de répondre aux questions et de tester des choses :)

**Comment by bokub** [comment]
Salut,

Tu t'es pas planté dans les volumes ?

Avec quelle commande tu lances l'addon ?

**Comment by sambonbonne** [comment]
J'ai peut-être mal compris ce que tu voulais demander par « quelle commande pour lancer l'addon », j'utilise un `StafulSet` sur Kubernetes donc je mets le manifest ici au besoin.

```yaml
apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: home-assistant-linky
  namespace: home-assistant

  labels:
    app.kubernetes.io/component: addon-linky
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/part-of: home-assistant

spec:
  replicas: 1
  revisionHistoryLimit: 5

  selector:
    matchLabels:
      app.kubernetes.io/component: addon-linky
      app.kubernetes.io/name: home-assistant
      app.kubernetes.io/part-of: home-assistant

  template:
    metadata:
      labels:
        app.kubernetes.io/component: addon-linky
        app.kubernetes.io/name: home-assistant
        app.kubernetes.io/part-of: home-assistant

    spec:
      containers:
        - name: home-assistant-linky
          image: localhost/home-assistant-linky:1.4.0

          envFrom:
            - secretRef:
                name: home-assistant-linky-environment

          volumeMounts:
            - name: test
              mountPath: /data
            - name: configuration
              mountPath: /data/options.json
              subPath: options.json

      volumes:
        - name: configuration
          projected:
            sources:
              - secret:
                  name: home-assistant-linky-configuration
                  items:
                    - key: options.json
                      path: options.json

  volumeClaimTemplates:
    - metadata:
        name: test
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
```
