### ISSUE TITLE
Souci de connexion au websocket homeassistant

### ISSUE THREAD

**Issue by ariault-blanchard** [bokub/ha-linky#62]
Hello,

J'essai tant bien que mal de configurer l'add-on (via le tag 1.5.0), j'ai bien suivi (selon moi) la documentation, malgré tout, j'ai un souci de connexion entre le container utilisé ha-linky (via standalone.Dockerfile) et mon container homeassistant.

voici l'erreur que j'ai :

```
2024-07-25 21:37:02.782 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 172.20.0.2 (172.20.0.2). Requested URL: '/api/websocket'. (None)
```

et le log de mon container ha-linky : 

```
$ docker logs -f ha-linky

HA Linky is starting
Cannot authenticate with Home Assistant
```

Les containers sont dans le même réseau, ils se joignent mais pour autant, homeassistant ne semble pas gérer la connexion ws...

Je pense que cela est surement dû à ma configuration HA avec WS car je n'ai encore jamais utilisé d'add-on avec ws.

Pour information, voici ma configuration (configuration.yaml) : 

```yaml
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 172.0.0.0/8
``` 

Ainsi que mon docker-compose.yaml : 

```
  ha-linky:
    container_name: ha-linky
    build:
      context: ../ha-linky
      dockerfile: standalone.Dockerfile
    environment:
      - SUPERVISOR_TOKEN=<TOKEN>
      - WS_URL=wss://<IP_HA>/api/websocket
      - TZ=Europe/Paris
    volumes:
      - "./linky-data:/data"
```
Y a-t-il une configuration manquante ?

Désolé je suis un peu nouveau sur HA donc je suis en pleine exploration mais plutôt à l'aise avec docker d'où mon questionnement sur la conf de HA.

Merci !
