### ISSUE TITLE
Historique des coûts pris en compte lors de l'import CSV des anciennes données ?

### ISSUE THREAD

**Issue by Bonbadil** [bokub/ha-linky#69]
Bonjour,
Votre plugin fonctionne magnifiquement, et la doc (du moment où je l'ai lu entièrement) est nickel.

À ce sujet et en aparté, ayant suivi la doc du README au fur et à mesure, j'ai fait d'abord la configuration de la synchro puis je l'ai exécuté.
Puis j'ai lu qu'il était possible de remonter plus d'historique et avec plus de précision avec l'import CSV, donc j'ai reset puis importé le CSV.
Puis j'ai lu qu'on pouvait définir le coût, alors j'ai configuré mes coûts, j'ai reset puis réimporté mon CSV.
Tout ceci est très bien, mais peut-être serait-il plus efficace de réordonner la doc ? Ou d'indiquer avant la configuration une phrase indiquant de lire l'import des CSV et la config des coûts avant de lancer la première synchro ? Mais cet avis est assez subjectif.

Bref, après avoir importé les 2 ans de consommation que m'autorise d'exporter Enedis avec les coûts de mon offre de base sur cette période :
```yaml
- price: 0.2516
  start_date: "2024-02-01"
- price: 0.2276
  start_date: "2023-08-01"
  end_date: "2024-01-31"
- price: 0.2062
  start_date: "2023-02-01"
  end_date: "2023-07-31"
```
je trouve bizarre l'absence de variation notable de couts entre les mois précédents et les mêmes de l'année d'avant (alors que le coût unitaire a prit +20%).
Alors je divise le cout total de ce mois de juin 2024 par la consommation et j'obtiens bien une valeur approchant les 0,2516 € (0,251525).
Mais si je divise le cout total du mois de juin **2023** par la consommation et j'obtiens aussi une valeur approchant les 0,2516 € (0,251614).
Serait-il possible que l'import d'ancienne donnée utilise le coût unitaire actuel pour calculer d'anciennes consommations ?

Merci et bon appétit. :)
