### ISSUE TITLE
Absence de l'entité _costs dans Home Assistant

### ISSUE THREAD

**Issue by Karl-V-HRR** [bokub/ha-linky#73]
Bonjour,
En premier lieu je tenais à vous remercier pour ce programme fort utile !

Je rencontre le problème suivant : je n'arrive à pas afficher les coûts dans Home Assistant ; lorsque j'essaye d'ajouter une « _entité de suivi des coûts totaux_ », comme indiqué dans la documentation, je n'ai aucune entité en __costs_ visible, seulement celles liées à la consommation en elle-même. Je suppose qu'il s'agit d'une erreur de configuration de ma part, mais je ne parviens pas à en déterminer la source.

J'ai installé Home Assistant ainsi que HA-Linky via Docker, dont je joins ci-dessous les fichiers compose, ainsi que le fichier options.json ; certaines entrées sont censurées avec « .... ». : 
```
services:
  homeassistant:
    container_name: Home_Assistant
    privileged: true
    image: ghcr.io/home-assistant/home-assistant:latest
    network_mode: host
    volumes:
      - /home/user/Docker/HomeAssistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    labels:
      - com.centurylinklabs.watchtower.monitor-only=true
    restart: unless-stopped
```

```
services:
  ha-linky:
    container_name: Linky
    image: ha-linky
    environment:
      - SUPERVISOR_TOKEN=....
      - WS_URL=wss://..../api/websocket
      - TZ=Europe/Paris
    volumes:
      - /home/user/Docker/Linky/data:/data
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=false
    networks:
      - Caddy
networks:
  Caddy:
    external: true
```
```
{
    "meters": [
        {
            "prm": "....",
            "token": "....",
            "name": "Linky consumption ....",
            "action": "sync",
            "production": false
        },
        {
            "prm": "....",
            "token": "....",
            "name": "Linky consumption ....",
            "action": "sync",
            "production": false
        }
    ],
    "costs": [
        {
            "price": "0.2064"
        }
    ]
}
```
Ci-dessous également les logs ; je me permets aussi de préciser que j'ai à plusieurs reprises « reconstruit » la base de données en changeant l'entrée _action_ dans le fichier options.json par _reset_ : 
```
Linky  | HA Linky is starting
Linky  | Connection with Home Assistant established
Linky  | PRM .... found in configuration for consumption
Linky  | [04/10 08:33] Synchronization started for consumption data
Linky  | Last saved statistic date is 02/10/2024
Linky  | Successfully retrieved consumption load curve from 2024-10-03 to 2024-10-04
Linky  | Data import returned 24 data points from 03/10/2024 to 03/10/2024
Linky  | PRM .... found in configuration for consumption
Linky  | [04/10 08:33] Synchronization started for consumption data
Linky  | Last saved statistic date is 02/10/2024
Linky  | Successfully retrieved consumption load curve from 2024-10-03 to 2024-10-04
Linky  | Data import returned 24 data points from 03/10/2024 to 03/10/2024
Linky  | Data synchronization planned every day at 06:33:58 and 09:33:58
Linky  | Connection with Home Assistant closed
```

Toutes mes excuses si la solution à ce problème paraît quelque peu triviale, & merci par avance pour votre aide !
